### ISSUE TITLE
Plugin Doesn't Load With Multiple Workspace Folders

### ISSUE THREAD

**Issue by savearray2** [Spence-S/vscode-linter-xo#3]
Hi there,

First off, I would like to really thank you for this new commit! It's a life saver for anyone using XO.

I have a workspace with multiple projects added to it, and the plugin only loads when the first workspace folder has a package.json with XO loaded in it.

If I have a Rust project, for example, as the first folder, then a Node.js project as the second folder, the plugin won't activate.

Please see the images below:

![image](https://user-images.githubusercontent.com/46784573/126648297-ed50bbec-4654-4027-85e2-f7e60666b95d.png)
![image](https://user-images.githubusercontent.com/46784573/126648446-caf06048-6422-438f-85f0-3a08cc5e9a1d.png)

**Comment by Spence-S** [comment]
Interesting, I don't use multi-root workspaces so I didn't test this, but I can get it working properly soon. Also note that, as you said, it does kind of work if the first folder has the library, however, I don't believe it will reload it when changing in between folders if you are using different xo versions in each folder. Just something to be aware of as you may get false linting errors in the editor based on that.

**Comment by savearray2** [comment]
Yeah, it would be nice if it loaded the rules individually for each workspace folder, as they may be different. :)
Again, thank you for you work. I imagine this took some time.

**Comment by savearray2** [comment]
@Spence-S 
I'd also be willing to fund this project directly to make sure that you get something for your work! Just let me know your preferred method.

**Comment by Spence-S** [comment]
> Yeah, it would be nice if it loaded the rules individually for each workspace folder, as they may be different. :)
> Again, thank you for you work. I imagine this took some time.

Just to be clear - it will always load the rules specific to the file that is open, but the internal rules may be different across XO versions. 

> I'd also be willing to fund this project directly to make sure that you get something for your work! Just let me know your preferred method.

Thank you so much! No obligation here I love to code, but you're support is greatly appreciated.
https://www.buymeacoffee.com/spence.s

**Comment by savearray2** [comment]
> Just to be clear - it will always load the rules specific to the file that is open, but the internal rules may be different across XO versions.

Thanks for the clarification!

> Thank you so much! No obligation here I love to code, but you're support is greatly appreciated.

Donation made :)

**Comment by Spence-S** [comment]
Closing this because we are moving development back the original repo and I am turning off issues here. This issue is already duplicated in the issues over there and I have a fix coming out soon. Thank you!
